module.exports = {
RECEIVEDISPLAYPLAYLIST: "RECEIVEDISPLAYPLAYLIST",
RECEIVEDNOPLAYLIST: "RECEIVEDNOPLAYLIST",
RECEIVEUSERPLAYLISTS: "RECEIVEUSERPLAYLISTS",
DELETEDTRACKFROMPLAYLIST: "DELETEDTRACKFROMPLAYLIST"
};
