module.exports = {
RECEIVEDISPLAYPLAYLIST: "RECEIVEDISPLAYPLAYLIST",
RECEIVETRACKPLAYLIST: "RECEIVETRACKPLAYLIST",
RECEIVEDNOPLAYLIST: "RECEIVEDNOPLAYLIST",
RECEIVEUSERPLAYLISTS: "RECEIVEUSERPLAYLISTS",
DELETEDTRACKFROMPLAYLIST: "DELETEDTRACKFROMPLAYLIST"
};
