module.exports = {
  RECEIVETRACKS : "RECEIVETRACKS",
  RECEIVEDISPLAYTRACK: "RECEIVEDISPLAYTRACK",
  DIDNOTFINDTRACK: "DIDNOTFINDTRACK",
  DIDNOTFETCHTRACKS: "DIDNOTFETCHTRACKS",
  RECEIVEUSERTRACKS: "RECEIVEUSERTRACKS"
};
